export const STATUSES_VALUES = {
    NOT_ASSIGNED: 1,
    OPEN: 2,
    AUTHORIZED: 3,
    CLOSED: 4,
    REJECTED: 5,
    CANCELED: 6,
    REJECTED_FROM_OPEN: 7,
}

export const LICENCES_STATUS = {
    REQUESTED: 0,
    APPROVED: 1,
}

export const ORDER_PAYMENT_STATUS_IDS = {
    PENDING: 1,
    PAID: 2,
}

export const STATUSES = {
    NOT_ASSIGNED: "NOT_ASSIGNED",
    OPEN: "OPEN",
    AUTHORIZED: "AUTHORIZED",
    CLOSED: "CLOSED",
    REJECTED: "REJECTED",
    CANCELED: "CANCELED",
    REJECTED_FROM_OPEN: "REJECTED_FROM_OPEN",
}

export const EMPTY_CLIENT = 0
export const EMPTY_PROVIDER = 0
export const EMPTY_PERSONAL = 0

export const CLIENTS_GROUPS = {
    UNASSIGNED: 1,
    ISSN: 2,
}

export const PASSENGER_TYPES = {
    HOLDER: "holder",
    COMPANION: "companion",
}

export const USER_PROFILES_IDS = {
    1: 'WEBMASTER',
    2: 'ADMIN',
    3: 'ENCUESTA SATISFACCION',
    4: 'VENTAS ADMINISTRACION',
    9: 'VENDEDOR',
}

export const USER_PROFILES_NAMES = {
    'WEBMASTER' : 1,
    'ADMIN': 2,
    'ENCUESTA SATISFACCION': 3,
    'VENTAS ADMINISTRACION': 4,
    'VENDEDOR': 9,
}

export const USER_PROFILES = {
    'WEBMASTER' : 'WEBMASTER',
    'ADMIN': 'ADMIN',
    'ENCUESTA_SATISFACCION': 'ENCUESTA SATISFACCION',
    'VENTAS_ADMINISTRADOR': 'VENTAS ADMINISTRACION',
    'VENDEDOR': 'VENDEDOR',
}

export const ISO_DOC_ESTADO = {
    OBSOLETO: 6,
    APROBADO: 4,
    ELABORADO: 1,
}
